# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerLoader
                                 A QGIS plugin
 LayerLoader é um plugin para QGIS que permite baixar e carregar automaticamente arquivos Shapefile a partir de uma URL. Ele facilita a obtenção e manipulação de dados geoespaciais ao automatizar o download, extração e carregamento das camadas no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-14
        copyright            : (C) 2025 by CP Albeny (ICA/IME) e Ten Ventura (IME)
        email                : albeny.filipe@ime.eb.br e ventura.luis@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerLoader class from file LayerLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_loader import LayerLoader
    return LayerLoader(iface)
